# DVC Pipeline for Face Mask Detection MLOps

stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/images.zip
      - config/config.yaml
    outs:
      - data/processed/train
      - data/processed/val
      - data/processed/test
    metrics:
      - data/processed/data_stats.json
    
  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed/train
      - data/processed/val
      - config/config.yaml
    outs:
      - models/mask_detector.h5
      - models/best_mask_detector.h5
    metrics:
      - models/metrics.json
    plots:
      - models/training_history.json
      
  model_evaluation:
    cmd: python src/predict.py --evaluate
    deps:
      - src/predict.py
      - models/mask_detector.h5
      - data/processed/test
      - config/config.yaml
    metrics:
      - models/evaluation_metrics.json
    plots:
      - models/evaluation_plots.json

plots:
  - models/training_history.json:
      x: epoch
      y:
        - accuracy
        - val_accuracy
      title: "Training History - Accuracy"
      
  - models/training_history.json:
      x: epoch  
      y:
        - loss
        - val_loss
      title: "Training History - Loss"

params:
- config/config.yaml
