stages:
  data_preprocessing:
    cmd: python src/training/data_processing.py
    deps:
      - src/training/data_processing.py
      - data/raw/images/
      - config/config.yaml
    outs:
      - data/processed/yolo_dataset/

  model_training:
    cmd: python src/training/model.py
    deps:
      - src/training/model.py
      - data/processed/yolo_dataset/
      - config/config.yaml
    outs:
      - models/yolov8_real_face_mask_detection/weights/best.pt
    metrics:
      - models/yolov8_real_face_mask_detection/training_metrics.json
    plots:
      - models/yolov8_real_face_mask_detection/training_plots.json

  model_evaluation:
    cmd: python src/inference/predictor.py --evaluate
    deps:
      - src/inference/predictor.py
      - models/yolov8_real_face_mask_detection/weights/best.pt
      - data/processed/yolo_dataset/test/images/
      - data/processed/yolo_dataset/test/labels/
      - config/config.yaml
    metrics:
      - models/yolov8_real_face_mask_detection/evaluation_metrics.json
    plots:
      - models/yolov8_real_face_mask_detection/evaluation_plots.json

plots:
  - models/yolov8_real_face_mask_detection/training_plots.json:
      x: epoch
      y:
        - accuracy
        - val_accuracy
        - loss
        - val_loss
      title: "YOLOv8 Face Mask Detection - Training History"
  - models/yolov8_real_face_mask_detection/training_history.json:
      x: epoch
      y:
        - loss
        - val_loss
      title: "Training History - Loss"

params:
  - config/config.yaml
