# DVC Pipeline for Professional Face Mask Detection MLOps

stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/images/
      - config/config.yaml
    outs:
      - data/processed/splits/
    metrics:
      - data/processed/data_stats.json
    
  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed/splits/
      - config/config.yaml
    outs:
      - models/best_mask_detector_imbalance_optimized.h5
    metrics:
      - models/training_metrics.json
    plots:
      - models/training_plots.json
      
  model_evaluation:
    cmd: python src/predict.py --evaluate
    deps:
      - src/predict.py
      - models/best_mask_detector_imbalance_optimized.h5
      - data/processed/splits/test/
      - config/config.yaml
    metrics:
      - models/evaluation_metrics.json
    plots:
      - models/evaluation_plots.json

plots:
  - models/training_plots.json:
      x: epoch
      y:
        - accuracy
        - val_accuracy
        - loss
        - val_loss
      title: "Professional Face Mask Detection - Training History"
      
  - models/training_history.json:
      x: epoch  
      y:
        - loss
        - val_loss
      title: "Training History - Loss"

params:
- config/config.yaml
