# Face Mask Detection MLOps Configuration

# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1
  image_size: [224, 224]
  batch_size: 32
  classes: ["with_mask", "without_mask"]

# Model Configuration
model:
  name: "face_mask_detector"
  architecture: "MobileNetV2"
  input_shape: [224, 224, 3]
  num_classes: 2
  dropout_rate: 0.5
  learning_rate: 0.001
  
# Training Configuration
training:
  epochs: 20
  early_stopping_patience: 5
  reduce_lr_patience: 3
  reduce_lr_factor: 0.2
  min_lr: 0.00001
  
# MLflow Configuration
mlflow:
  experiment_name: "face_mask_detection"
  run_name_prefix: "mask_detector"
  tracking_uri: "http://localhost:5000"
  artifact_location: "./mlruns"
  
# Monitoring Configuration
monitoring:
  drift_threshold: 0.1
  performance_threshold: 0.85
  log_predictions: true
  alert_email: "admin@example.com"
  
# Deployment Configuration
deployment:
  model_stage: "Production"
  api_host: "0.0.0.0"
  api_port: 8080
  max_batch_size: 10
  timeout: 30
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
