name: Weekly Retraining

on:
  schedule:
    - cron: "0 21 * * 0" # Every Sunday at 21:00 UTC
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run retraining script
        run: python scripts/retrain.py
      # Optionally: commit/push updated models or data
